classification_loss:
    _target_: torch.nn.CrossEntropyLoss

# additional losses are optional and are used to regularize the model
# they can be used for moes or residual models
# for more info see peekvit/losses.py
additional_losses:
    distr_prior_loss:
        _target_:  peekvit.utils.losses.AViTDPriorLoss
        target_depth: 11
        weight: 0.2
    ponder_loss:
        _target_:  peekvit.utils.losses.AViTPonderLoss
        weight: 0.0005
