classification_loss:
    _target_: torch.nn.CrossEntropyLoss

additional_losses:
    mse:
        _target_:  peekvit.utils.losses.MSELoss
        weight: 0.1
        strict: False
    mse2:
        _target_: peekvit.utils.losses.MSELoss
        weight: 0.1