_target_: peekvit.models.adapt.AdaptivePointCloudTransformer
num_points: ${dataset.num_points}
num_classes: ${dataset.num_classes}
hidden_dim: 128
mlp_dim: 256
num_layers: 4
num_heads: 4
num_class_tokens: 1
drop_layers: [0, 1, 2, 3]
drop_target: 0.3
warmup_start: 20
warmup_steps: 20