_target_:  peekvit.models.adavit.AdaptiveVisionTransformer
image_size: 224
patch_size: 16
num_layers: 12
hidden_dim: 384
mlp_dim: 1536
num_heads: 6
num_classes: ${dataset.num_classes}
eps: 0.01
gate_scale: 10
gate_center: 30
timm_pretrained_weights: ['facebookresearch/deit:main', 'deit_small_patch16_224']