_target_:  peekvit.models.adavit.AdaptiveVisionTransformer
image_size: 224
patch_size: 16
num_layers: 12
hidden_dim: 192
mlp_dim: 768
num_heads: 3
num_classes: ${dataset.num_classes}
eps: 0.01
gate_scale: 10 #10
gate_center: 5 #30
timm_pretrained_weights: ['facebookresearch/deit:main', 'deit_tiny_patch16_224'] #/home/aledev/projects/peekvit-workspace/adavit_pretrained_weights/a-vit-weights/tiny-10-30.pth