_target_: peekvit.models.batchrankvit.BatchRankVisionTransformer
num_classes: ${dataset.num_classes}
image_size: ${dataset.image_size}
patch_size: 16
hidden_dim: 192
mlp_dim: 768
num_layers: 12
num_heads: 3
timm_pretrained_weights: null #['facebookresearch/deit:main', 'deit_tiny_patch16_224']
drop_mode: 'single'

