_target_: peekvit.models.rankvit.RankVisionTransformer
num_classes: ${dataset.num_classes}
image_size: ${dataset.image_size}
patch_size: 8
hidden_dim: 256
mlp_dim: 768
num_layers: 4
num_heads: 4
attention_dropout: 0.1
dropout: 0.1
