_target_: peekvit.models.rankvit.RankVisionTransformer
num_classes: ${dataset.num_classes}
image_size: ${dataset.image_size}
patch_size: 16
hidden_dim: 768
mlp_dim: 3072
num_layers: 12
num_heads: 12
torch_pretrained_weights: ViT_B_16_Weights['IMAGENET1K_V1']