_target_: peekvit.data.flowers102.Flowers102Dataset
root: '/hdd2/aledev/datasets/flowers102'
image_size: 224                                   # used by default by model as well
split: 'train+test'
download: True
num_classes: 102                                  # used by default by model as well  
augmentation_ops: 2                               # number of augmentation operations to apply        
augmentation_magnitude: 9                         # magnitude of augmentation operations     