_target_: peekvit.data.food101.Food101Dataset
root: '/hdd2/aledev/datasets/food101'
image_size: 224                                   # used by default by model as well
split: 'train+test'
download: True
num_classes: 101                                  # used by default by model as well  
augmentation_ops: 2                               # number of augmentation operations to apply        
augmentation_magnitude: 9                         # magnitude of augmentation operations     