train_batch_size: 128
eval_batch_size: 128
lr: 1e-3
num_epochs: 100
eval_every: 10
checkpoint_every: 10
reinit_class_tokens: True
num_workers: 4
classification_loss: torch.nn.CrossEntropyLoss
val_budgets: [0.25, 0.85]
