train_batch_size: 128
eval_batch_size: 128
lr: 1e-3
num_epochs: 100
eval_every: 10                    # -1 for no evaluation
checkpoint_every: 10              # -1 for no checkpointing
reinit_class_tokens: False         # reinitialize class tokens before training
train_backbone: True             # train backbone. If false, only train only head, masking module, budget tokens and class tokens.
num_workers: 4
val_budgets: null           # budgets to use during validation