train_batch_size: 64
eval_batch_size: 64
clip_grad_norm: 1.0
num_epochs: 100
eval_every: 10                    # -1 for no evaluation
checkpoint_every: 10              # -1 for no checkpointing
plot_masks_every: 10              # -1 for no plotting
num_images_to_plot: 10
reinit_class_tokens: True         # reinitialize class tokens before training
train_backbone: True             # train backbone. If false, only train only head, masking module, budget tokens and class tokens.
num_workers: 16
val_budgets: [0.2, 0.8]           # budgets to use during validation
blocks_to_remove: []
temperature: 5.0
alpha: 0.5
mse_distill: True
kl_distill: False