train_batch_size: 128
eval_batch_size: 128
lr: 1e-3
num_epochs: 100
eval_every: 10                    # -1 for no evaluation
checkpoint_every: 10              # -1 for no checkpointing
plot_masks_every: 10              # -1 for no plotting
num_images_to_plot: 10
reinit_class_tokens: True         # reinitialize class tokens before training
train_backbone: False             # train backbone. If false, only train only head, masking module, budget tokens and class tokens.
num_workers: 4
val_budgets: [0.2, 0.8]           # budgets to use during validation
