train_batch_size: 256
eval_batch_size: 256
clip_grad_norm: 1.0
num_epochs: 0
eval_every: 1                    # -1 for no evaluation
checkpoint_every: 10              # -1 for no checkpointing
plot_masks_every: -1              # -1 for no plotting
num_images_to_plot: 10
reinit_class_tokens: False         # reinitialize class tokens before training
train_backbone: False             # train backbone. If false, only train only head, masking module, budget tokens and class tokens.
num_workers: 4
val_budgets: [0.98]           # budgets to use during validation
train_budgets: [0.98]               # budgets to use during training
remove_layers: False
