# PATHS
#Structure of the workspace:
#
#workspace
#├── configs/
#│   └── config.yaml
#├── runs/
#    ├── YYYY-mm-dd-hh-MM-SS/
#        ├── checkpoints/
#        ├── images/    
#        ├── logs.txt
#

workspace: '/home/aledev/projects/peekvit-workspace/peekvit'
experiments_dir: '${workspace}/runs/'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'

device: 'cuda:0'
seed: 0
load_from: '/home/aledev/projects/peekvit-workspace/peekvit/runs/2024-01-17-18-31-37'

hydra:
  run:
    dir: '${experiments_dir}/${experiment_name}/'



defaults:
  - logger: local
  - dataset: imagenette
  - model: residualvit
  - training: base
  - loss: crossentropy_2
  - extra_loss: null
  - noise: null
  - _self_





