# PATHS
#Structure of the workspace:
#
#workspace
#├── configs/
#│   └── config.yaml
#├── runs/
#    ├── YYYY-mm-dd-hh-MM-SS/
#        ├── checkpoints/
#        ├── images/    
#        ├── logs.txt
#

workspace: '/home/aledev/projects/peekvit-workspace/peekvit'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'
experiments_dir: '${workspace}/runs/'

hydra:
  run:
    dir: '${experiments_dir}/${experiment_name}/'


device: 'cuda:0'
seed: 0
load_from: 


logger:
  _target_: peekvit.utils.logging.WandbLogger
  wandb_entity: 'aledevo'
  wandb_project: 'peekvit'
  wandb_run: null



dataset:
  _target_: peekvit.data.dataset.Imagenette
  root: '/home/aledev/projects/moe-workspace/data/imagenette'
  image_size: 160


model:
  _target_: peekvit.models.vit.VisionTransformer
  image_size: 160
  patch_size: 16
  num_classes: 10
  hidden_dim: 512
  mlp_dim: 512
  num_layers: 4
  num_heads: 8


training:
  train_batch_size: 128
  eval_batch_size: 128
  lr: 1e-3
  num_epochs: 10
  eval_every: 1
  checkpoint_every: 1
  reinit_class_tokens: True
  num_workers: 4


main_criterion:
  _target_: torch.nn.CrossEntropyLoss

noise: null




