# PATHS
#Structure of the workspace:
#
#workspace
#├── configs/
#│   └── config.yaml
#├── runs/
#    ├── YYYY-mm-dd-hh-MM-SS/
#        ├── checkpoints/
#        ├── images/    
#        ├── logs.txt
#

workspace: '/home/aledev/projects/peekvit-workspace/peekvit'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'
experiments_dir: '${workspace}/runs/'

hydra:
  run:
    dir: '${experiments_dir}/${experiment_name}/'

device: 'cuda:0'
seed: 0
load_from: '/home/aledev/projects/peekvit-workspace/peekvit/runs/2024-01-17-18-31-37'



defaults:
  - logger: wandb
  - dataset: imagenette
  - model: visiontransformer
  - training: base


main_criterion:
  _target_: torch.nn.CrossEntropyLoss

noise: null




