# PATHS
#Structure of the workspace:
#
#workspace
#├── configs/
#│   └── config.yaml
#├── runs/
#    ├── YYYY-mm-dd-hh-MM-SS/
#        ├── checkpoints/
#        ├── images/    
#        ├── logs.txt
#

workspace: '/home/aledev/projects/peekvit-workspace/peekvit'
experiments_dir: '${workspace}/runs'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'

device: 'cuda:0'
seed: 0
load_from: '${experiments_dir}/2024_01_04_16_00_57_single_budget_base'


hydra:
  run:
    dir: ${load_from}



defaults:
  - logger: wandb
  - dataset: imagenette
  - noise: no_noise 
  - test: base
  - _self_





