# Structure of the workspace:
#
# workspace
# ├── configs/
# │   └── config.yaml
# ├── runs/
#     ├── YYYY-mm-dd-hh-MM-SS/
#         ├── checkpoints/
#         ├── images/    
#         ├── logs.txt
#


workspace: '/home/giordano/Documenti/Piagnina/peekvit'
experiments_dir: '${workspace}/runs/'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'

device: 'cuda:0'
seed: 0
load_from: null

hydra:
  run:
    dir: '${experiments_dir}/${experiment_name}/'



defaults:
  - logger: wandb
  - dataset: imagenette
  - teacher_model: deit_s_16_224
  - student_model: vit_distill
  - training: distill
  - optimizer: adam
  - scheduler: null
  - loss: crossentropy
  - noise: no_noise 
  - _self_





