# PATHS
#Structure of the workspace:
#
#workspace
#├── configs/
#│   └── config.yaml
#├── runs/
#    ├── YYYY-mm-dd-hh-MM-SS/
#        ├── checkpoints/
#        ├── images/    
#        ├── logs.txt
#

workspace: '/home/aledev/projects/peekvit-workspace/peekvit'
experiments_dir: '${workspace}/runs/'
experiment_name: '${now:%Y-%m-%d-%H-%M-%S}'

device: 'cuda:0'
seed: 0
load_from: '/home/aledev/projects/peekvit-workspace/peekvit/runs/2023_12_21_10_12_06_base'

hydra:
  run:
    dir: '${experiments_dir}/${experiment_name}/'



defaults:
  - logger: wandb
  - dataset: imagenette
  - model: residualvit
  - training: base
  - loss: crossentropy_mse
  - noise: no_noise 
  - _self_





